### ISSUE TITLE
Error Log: babel-node index.js

### ISSUE THREAD

**Issue by Feeona** [Gravestorm/Gravebot#34] opened 2016-01-06 10:43 UTC
Greetings,

My apologies if you're not actually taking error logs, since this is a new repo I was unsure if my error was self inflicted or a matter you could help with.

I've tried both launching this on Windows and Linux and unfortunately cannot get it to load. My deepest apologies if I'm being a dumbass and have missed something simple.

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/feeona/.nvm/versions/node/v5.0.0/bin/node',
1 verbose cli   '/home/feeona/.nvm/versions/node/v5.0.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle gravebot@1.2.0~prestart: gravebot@1.2.0
6 silly lifecycle gravebot@1.2.0~prestart: no script for prestart, continuing
7 info lifecycle gravebot@1.2.0~start: gravebot@1.2.0
8 verbose lifecycle gravebot@1.2.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle gravebot@1.2.0~start: PATH: /home/feeona/.nvm/versions/node/v5.0.0/lib/node_modules/npm/bin/node-gyp-bin:/home/feeona/Downloads/Gravebot-master/node_modules/.bin:/home/feeona/.nvm/versions/node/v5.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle gravebot@1.2.0~start: CWD: /home/feeona/Downloads/Gravebot-master
11 silly lifecycle gravebot@1.2.0~start: Args: [ '-c', 'babel-node index.js' ]
12 silly lifecycle gravebot@1.2.0~start: Returned: code: 1  signal: null
13 info lifecycle gravebot@1.2.0~start: Failed to exec start script
14 verbose stack Error: gravebot@1.2.0 start: `babel-node index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/feeona/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/feeona/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid gravebot@1.2.0
16 verbose cwd /home/feeona/Downloads/Gravebot-master
17 error Linux 3.19.0-25-generic
18 error argv "/home/feeona/.nvm/versions/node/v5.0.0/bin/node" "/home/feeona/.nvm/versions/node/v5.0.0/bin/npm" "start"
19 error node v5.0.0
20 error npm  v3.3.6
21 error code ELIFECYCLE
22 error gravebot@1.2.0 start: `babel-node index.js`
22 error Exit status 1
23 error Failed at the gravebot@1.2.0 start script 'babel-node index.js'.
23 error This is most likely a problem with the gravebot package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     babel-node index.js
23 error You can get their info via:
23 error     npm owner ls gravebot
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by dustinblackman** [comment] 2016-01-06 12:56
Install babel node globally, then try running index.js. That error log doesn't tell me much.

```bash
npm install -g babel-node
babel-node index.js
```

If that doesn't work then try node `4.2.4`. Node 4 has LTS and is the reason we use it in local and production.

**Comment by Feeona** [comment] 2016-01-07 03:39
Hi Dustin,

Thanks for the quick reply.  I gave the above a shot and unfortunately still no dice, I've tried messing around with both the local and global settings for babel but it seems I'm at a dead end.  I also loaded up node 4.2.3 to no avail. 

Thanks for your help, if you ever find out the issue please throw me a line. :)

**Comment by dustinblackman** [comment] 2016-01-07 04:48
@Feeona I know the above command didn't work, but can you give me the log it's outputting please?

**Comment by Feeona** [comment] 2016-01-07 07:49
Oddly enough it's the exact same log so I'm afraid nothing has changed.

**Comment by kodycode** [comment] 2016-01-07 08:23
I've also had this issue in the previous of Gravebot and what fixed it for me was downloading the new Babel version. Not sure how or if that actually fixed it since I tinkered with a lot of other things, but as of this new update I'm facing the problem once again and I don't exactly know how to fix it again.

**Comment by dustinblackman** [comment] 2016-01-07 12:57
I've updated babel to the lastest with a few others things. Run `npm install` and try again.

**Comment by kodycode** [comment] 2016-01-07 21:59
@dustinblackman For me, windows. I also updated gravebot and ran `npm install` but the issue is still oddly occurring.

**Comment by dustinblackman** [comment] 2016-01-07 22:57
@kodycode Do you have a different output other then the one above?

**Comment by kodycode** [comment] 2016-01-07 23:21
It appears to be the same, although I noticed I'm using different versions of npm and node. 

>0 info it worked if it ends with ok
>1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Kody-PC\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle gravebot@1.2.0~prestart: gravebot@1.2.0
6 silly lifecycle gravebot@1.2.0~prestart: no script for prestart, continuing
7 info lifecycle gravebot@1.2.0~start: gravebot@1.2.0
8 verbose lifecycle gravebot@1.2.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle gravebot@1.2.0~start: PATH: C:\Users\Kody-PC\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Kody-PC\Desktop\Gravebot-master\node_modules\.bin;C:\ffmpeg\ffmpeg-20160102-git-7812997-win64-static\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\Kody-PC\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\nodejs\;C:\Users\Kody-PC\AppData\Roaming\npm;C:\Program Files (x86)\Livestreamer;C:\Program Files (x86)\nodejs\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\Kody-PC\.dnx\bin;C:\Users\Kody-PC\AppData\Local\Programs\Python\Python35-32\Scripts\;C:\Users\Kody-PC\AppData\Local\Programs\Python\Python35-32\;C:\ffmpeg\ffmpeg-20160102-git-7812997-win64-static\bin;C:\Program Files\Git;C:\Program Files\Git\git-cmd.exe;C:\ffmpeg\ffmpeg-20160102-git-7812997-win64-static\;C:\Users\Kody-PC\AppData\Roaming\livestreamer;C:\Users\Kody-PC\AppData\Local\Programs\Python\Python35-32;C:\Users\Kody-PC\AppData\Local\Programs\Python\Python35-32\python.exe;C:\Python27;C:\Python27\python.exe;C:\Users\Kody-PC\AppData\Roaming\npm;C:\Program Files\nodejs
10 verbose lifecycle gravebot@1.2.0~start: CWD: C:\Users\Kody-PC\Desktop\Gravebot-master
11 silly lifecycle gravebot@1.2.0~start: Args: [ '/d /s /c', 'babel-node index.js' ]
12 silly lifecycle gravebot@1.2.0~start: Returned: code: 1  signal: null
13 info lifecycle gravebot@1.2.0~start: Failed to exec start script
14 verbose stack Error: gravebot@1.2.0 start: `babel-node index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Kody-PC\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Kody-PC\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid gravebot@1.2.0
16 verbose cwd C:\Users\Kody-PC\Desktop\Gravebot-master
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Kody-PC\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v4.2.4
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error gravebot@1.2.0 start: `babel-node index.js`
22 error Exit status 1
23 error Failed at the gravebot@1.2.0 start script 'babel-node index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the gravebot package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     babel-node index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs gravebot
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls gravebot
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Feeona** [comment] 2016-01-08 01:41
I'd like to chime in that I had the error with  libxmljs on windows which is why I moved to Unbuntu in which I have the exact same log as Kody.

**Comment by dustinblackman** [comment] 2016-01-08 05:19
Thanks for the info guys.

Two ideas come to mind. First, I just put up a branch that drops the `babel-node` binary. I plan on merging the branch tomorrow, but you're more then welcome to give it a try before hand. https://github.com/Gravestorm/Gravebot/pull/61

Second is not all NPM modules are compatible with npm v3, some of which install but then will throw an error when requiring. Try with npm 2 if the branch doesn't work. `npm install -g npm@2.14.14`

**Comment by kodycode** [comment] 2016-01-08 07:15
After wrestling with the files for a bit with the new branch, it finally worked! I also used npm version 2.14.14.

**Comment by Feeona** [comment] 2016-01-08 09:22
I`ll wait until the merged branch is up then give it a whirl, excited to try!

**Comment by dustinblackman** [comment] 2016-01-08 14:06
Glad things worked with v2. :)
Branch is merged, I'm going to close this issue. If the problems persist I'll open it again. Thanks for sticking through.

**Closed by dustinblackman** 2016-01-08 14:06 UTC
Labels: question
